export const product = [
  {
    id: 1,
    title: "زانو 90 درجه جوشی بدون درز شعاع بلند رده 40 بنکن (BENKAN)",
    discount: 20,
    size: 3,
    price: 100000,
    grouping: "لوله فلزی",
    href: "لوله مانیسمان (فولادی بدون درز)",
  },
  {
    id: 2,
    title: "لوله مانیسمان",
    discount: 30,
    size: 2,
    price: 300000,
    grouping: "لوله فلزی",
    href: "لوله مانیسمان",
  },
  {
    id: 3,
    title: "زانو 90 درجه جوشی بدون درز شعاع بلند رده 40 بنکن (BENKAN)",
    discount: 20,
    size: 3,
    price: 400000,
    grouping: "لوله فلزی",
    href: "لوله مانیسمان (فولادی بدون درز)",
  },
  {
    id: 4,
    title: "لوله مانیسمان",
    discount: 30,
    size: 2,
    price: 800000,
    grouping: "لوله فلزی",
    href: "لوله مانیسمان",
  },
];

export const products = [
  {
    id: 1,
    title: "زانو 90 درجه جوشی بدون درز شعاع بلند رده 40 بنکن (BENKAN)",
    discount: 20,
    size: 3,
    price: 100000,
    grouping: "لوله فلزی",
    href: "لوله مانیسمان (فولادی بدون درز)",
    types: [
      {
        id: 1,
        size: 1,
        type: "جوشی",
        unit: "شاخه 6 متری",
        detail: {
          "نوع اتصال": " جوشی",
          تلرانس: " ٪5±",
          "نوع(تایپ)": "سبک",
        },
        price: 200000,
        sale: true,
        totalPrice: "",
      },
      {
        id: 2,
        size: 5,
        type: "جوشی",
        unit: "شاخه 6 متری",
        detail: {
          "نوع اتصال": " جوشی",
          تلرانس: " ٪5±",
          "نوع(تایپ)": "سبک",
        },
        price: 400000,
        sale: true,
        totalPrice: "",
      },
    ],
  },
  {
    id: 2,
    title: "لوله مانیسمان بدون درز جوشی سبک با تلرانس: ٪5± اهواز",
    discount: 15,
    size: 12,
    price: 400000,
    grouping: "لوله فلزی",
    href: "لوله مانیسمان (فولادی بدون درز)",
    types: [
      {
        id: 3,
        size: 14,
        type: "جوشی",
        unit: "شاخه 6 متری",
        detail: {
          "نوع اتصال": " جوشی",
          تلرانس: " ٪5±",
          "نوع(تایپ)": "سبک",
        },
        price: 600000,
        sale: true,
        totalPrice: "",
      },
      {
        id: 4,
        size: 6,
        type: "جوشی",
        unit: "شاخه 6 متری",
        detail: {
          "نوع اتصال": " جوشی",
          تلرانس: " ٪5±",
          "نوع(تایپ)": "سبک",
        },
        price: 1400000,
        sale: true,
        totalPrice: "",
      },
      {
        id: 5,
        size: 15,
        type: "جوشی",
        unit: "شاخه 6 متری",
        detail: {
          "نوع اتصال": " جوشی",
          تلرانس: " ٪5±",
          "نوع(تایپ)": "سبک",
        },
        price: 4500000,
        sale: true,
        totalPrice: "",
      },
    ],
  },
];

export const data = [
  {
    id: 1,
    image: "/images/static/Product-photo.jpg",
    title: "کابل تبدیل USB به لایتنینگ پینزی مدل L6 طول 1 متر",
    alt: "Product",
    price: 60000,
    discount: 20,
    available: true,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 120000 },
    ],
  },
  {
    id: 2,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ 15 اینچی لنوو مدل Ideapad",
    alt: "Product",
    price: 870000,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 780000 },
    ],
  },
  {
    id: 3,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ 15 اینچی لنوو مدل Ideapad 330 - E",
    alt: "Product",
    price: 70000,
    available: true,
    discount: 10,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 70000 },
    ],
  },
  {
    id: 4,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ 15 لنوو مدل Ideapad 330 - E",
    alt: "Product",
    price: 80000,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 80000 },
    ],
  },
  {
    id: 5,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ  مدل Ideapad 330 - E",
    alt: "Product",
    price: 130000,
    discount: 15,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 130000 },
    ],
  },
  {
    id: 6,
    image: "/images/static/Product-photo-02.jpg",
    title: "لپ تاپ  مدل Ideapad 330 - E",
    alt: "Product",
    price: 130000,
    discount: 15,
    available: false,
    description: [
      { title: "رنگ", value: "مشکی" },
      { title: "قیمت واحد", value: 130000 },
    ],
  },
];

export const prods = [
  {
    title: "لوله فلزی",
    img: "/static/images/1_20220907224233.969_20221023162800.051_20221127143218.635.svg",
    href: "/",
    id: 1,
    des: [
      { title: "لوله مانیسمان (فولادی بدون درز)", id: 1 },
      { title: "لوله گالوانیزه گرم", id: 2 },
      { title: "موارد بیشتر", id: 3 },
    ],
  },
  {
    title: "اتصالات فلزی",
    img: "/static/images/7.svg",
    href: "/",
    id: 2,
    des: [
      { title: "لوله مانیسمان (فولادی بدون درز)", id: 1 },
      { title: "لوله گالوانیزه گرم", id: 2 },
      { title: "موارد بیشتر", id: 3 },
    ],
  },
  {
    title: "فلنج و اتصالات",
    img: "/static/images/4.svg",
    href: "/",
    id: 3,
    des: [
      { title: "لوله مانیسمان (فولادی بدون درز)", id: 1 },
      { title: "لوله گالوانیزه گرم", id: 2 },
      { title: "موارد بیشتر", id: 3 },
    ],
  },
];
